/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedRequirementsRouteImport } from './routes/_authenticated/requirements'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProcessClausesRouteImport } from './routes/_authenticated/process-clauses'
import { Route as AuthenticatedPrinciplesRouteImport } from './routes/_authenticated/principles'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated/organizations'
import { Route as AuthenticatedMyAssessmentsRouteImport } from './routes/_authenticated/my-assessments'
import { Route as AuthenticatedLevelsRouteImport } from './routes/_authenticated/levels'
import { Route as AuthenticatedFrameworksRouteImport } from './routes/_authenticated/frameworks'
import { Route as AuthenticatedFrameworkVersionsRouteImport } from './routes/_authenticated/framework-versions'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssessmentCriteriaRouteImport } from './routes/_authenticated/assessment-criteria'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequirementsRoute =
  AuthenticatedRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessClausesRoute =
  AuthenticatedProcessClausesRouteImport.update({
    id: '/process-clauses',
    path: '/process-clauses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrinciplesRoute = AuthenticatedPrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAssessmentsRoute =
  AuthenticatedMyAssessmentsRouteImport.update({
    id: '/my-assessments',
    path: '/my-assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLevelsRoute = AuthenticatedLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrameworksRoute = AuthenticatedFrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrameworkVersionsRoute =
  AuthenticatedFrameworkVersionsRouteImport.update({
    id: '/framework-versions',
    path: '/framework-versions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssessmentCriteriaRoute =
  AuthenticatedAssessmentCriteriaRouteImport.update({
    id: '/assessment-criteria',
    path: '/assessment-criteria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/assessment-criteria': typeof AuthenticatedAssessmentCriteriaRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/framework-versions': typeof AuthenticatedFrameworkVersionsRoute
  '/frameworks': typeof AuthenticatedFrameworksRoute
  '/levels': typeof AuthenticatedLevelsRoute
  '/my-assessments': typeof AuthenticatedMyAssessmentsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/principles': typeof AuthenticatedPrinciplesRoute
  '/process-clauses': typeof AuthenticatedProcessClausesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/assessment-criteria': typeof AuthenticatedAssessmentCriteriaRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/framework-versions': typeof AuthenticatedFrameworkVersionsRoute
  '/frameworks': typeof AuthenticatedFrameworksRoute
  '/levels': typeof AuthenticatedLevelsRoute
  '/my-assessments': typeof AuthenticatedMyAssessmentsRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/principles': typeof AuthenticatedPrinciplesRoute
  '/process-clauses': typeof AuthenticatedProcessClausesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/requirements': typeof AuthenticatedRequirementsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/assessment-criteria': typeof AuthenticatedAssessmentCriteriaRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/framework-versions': typeof AuthenticatedFrameworkVersionsRoute
  '/_authenticated/frameworks': typeof AuthenticatedFrameworksRoute
  '/_authenticated/levels': typeof AuthenticatedLevelsRoute
  '/_authenticated/my-assessments': typeof AuthenticatedMyAssessmentsRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/principles': typeof AuthenticatedPrinciplesRoute
  '/_authenticated/process-clauses': typeof AuthenticatedProcessClausesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/requirements': typeof AuthenticatedRequirementsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unauthorized'
    | '/assessment-criteria'
    | '/assessments'
    | '/framework-versions'
    | '/frameworks'
    | '/levels'
    | '/my-assessments'
    | '/organizations'
    | '/principles'
    | '/process-clauses'
    | '/reports'
    | '/requirements'
    | '/reviews'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/unauthorized'
    | '/assessment-criteria'
    | '/assessments'
    | '/framework-versions'
    | '/frameworks'
    | '/levels'
    | '/my-assessments'
    | '/organizations'
    | '/principles'
    | '/process-clauses'
    | '/reports'
    | '/requirements'
    | '/reviews'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/unauthorized'
    | '/_authenticated/assessment-criteria'
    | '/_authenticated/assessments'
    | '/_authenticated/framework-versions'
    | '/_authenticated/frameworks'
    | '/_authenticated/levels'
    | '/_authenticated/my-assessments'
    | '/_authenticated/organizations'
    | '/_authenticated/principles'
    | '/_authenticated/process-clauses'
    | '/_authenticated/reports'
    | '/_authenticated/requirements'
    | '/_authenticated/reviews'
    | '/_authenticated/settings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requirements': {
      id: '/_authenticated/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof AuthenticatedRequirementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/process-clauses': {
      id: '/_authenticated/process-clauses'
      path: '/process-clauses'
      fullPath: '/process-clauses'
      preLoaderRoute: typeof AuthenticatedProcessClausesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/principles': {
      id: '/_authenticated/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof AuthenticatedPrinciplesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-assessments': {
      id: '/_authenticated/my-assessments'
      path: '/my-assessments'
      fullPath: '/my-assessments'
      preLoaderRoute: typeof AuthenticatedMyAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/levels': {
      id: '/_authenticated/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof AuthenticatedLevelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frameworks': {
      id: '/_authenticated/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof AuthenticatedFrameworksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/framework-versions': {
      id: '/_authenticated/framework-versions'
      path: '/framework-versions'
      fullPath: '/framework-versions'
      preLoaderRoute: typeof AuthenticatedFrameworkVersionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-criteria': {
      id: '/_authenticated/assessment-criteria'
      path: '/assessment-criteria'
      fullPath: '/assessment-criteria'
      preLoaderRoute: typeof AuthenticatedAssessmentCriteriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssessmentCriteriaRoute: typeof AuthenticatedAssessmentCriteriaRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedFrameworkVersionsRoute: typeof AuthenticatedFrameworkVersionsRoute
  AuthenticatedFrameworksRoute: typeof AuthenticatedFrameworksRoute
  AuthenticatedLevelsRoute: typeof AuthenticatedLevelsRoute
  AuthenticatedMyAssessmentsRoute: typeof AuthenticatedMyAssessmentsRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedPrinciplesRoute: typeof AuthenticatedPrinciplesRoute
  AuthenticatedProcessClausesRoute: typeof AuthenticatedProcessClausesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRequirementsRoute: typeof AuthenticatedRequirementsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssessmentCriteriaRoute: AuthenticatedAssessmentCriteriaRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedFrameworkVersionsRoute: AuthenticatedFrameworkVersionsRoute,
  AuthenticatedFrameworksRoute: AuthenticatedFrameworksRoute,
  AuthenticatedLevelsRoute: AuthenticatedLevelsRoute,
  AuthenticatedMyAssessmentsRoute: AuthenticatedMyAssessmentsRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedPrinciplesRoute: AuthenticatedPrinciplesRoute,
  AuthenticatedProcessClausesRoute: AuthenticatedProcessClausesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRequirementsRoute: AuthenticatedRequirementsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
