// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lovkhqpxaibrzyztmcky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvdmtocXB4YWlicnp5enRtY2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2MjQ5OTcsImV4cCI6MjEwMDIwMDk5N30.-AZjtOOtCFcSOQulmLblJ58DhHu1xtO0xup0aJk2IY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});